export const QUERY_SELECT = "QUERY_SELECT";
export const REQUEST_TEAMSDATA = "REQUEST_TEAMSDATA";
export const RECEIVE_TEAMSDATA = "RECEIVE_TEAMSDATA";
export const RECEIVE_TEAMSDATA_ERROR = "RECEIVE_TEAMSDATA_ERROR";
export const REQUEST_USERSDATA = "REQUEST_USERSDATA";
export const RECEIVE_USERSDATA = "RECEIVE_USERSDATA";
export const RECEIVE_USERSDATA_ERROR = "RECEIVE_USERSDATA_ERROR";
